### PR TITLE
small fixes

### LINKED ISSUE #177: Searching a long list of PA numbers
I searched a list of about 100 PA numbers using the List function. 
Some numbers came up three or four times (confirmed to be only in list 1X) and the list on the left was cutoff making it hard to know what to select.  Just passing this along. 
Screenshot 2020-05-03 09 00 53

Here is the list if interested. 

PA0024
PA0150
PA0161
PA0381
PA0514
PA0518
PA0519
PA0523
PA0524
PA0525
PA0526
PA0541
PA0542
PA0607
 
PA0781
PA0963
PA1556
PA1581
PA1673
PA1746
PA1853
PA1899
PA1900
PA1922
PA1925
PA1959
PA1999
PA2019
PA2193
PA2259
PA2386
PA2392
PA2393
PA2411
PA2412
PA2425
PA2426
PA2427
PA2446
PA2663
PA2679
PA2753
PA2851
PA2945
PA2970
PA3126
 
PA3196
PA3209
PA3244
 
PA3308
PA3309
PA3332
PA3337
PA3397
PA3410
PA3431
PA3432
PA3472
PA3599
PA3600
PA3601
PA3647
PA3655
PA3656
PA3685
PA3686
PA3743
PA3744
PA3745
PA3746
PA3818
PA3822
PA3967
PA4063
PA4064
PA4065
PA4067
PA4141
PA4245
PA4261
PA4262
PA4264
PA4268
PA4274
PA4348
PA4352
PA4429
PA4432
PA4433
PA4438
 
PA4563
PA4567
PA4568
PA4602
PA4670
PA4671
PA4672
 
PA4741
PA4746
PA4748
PA4834
PA4835
PA4836
PA4837
PA4838
PA4855
PA4896
PA4932
PA4933
PA4934
PA4935
PA5049
PA5051
PA5118
PA5129
PA5139
PA5315
PA5316
PA5426
PA5427
PA5470
PA5475
PA5504
PA5505
PA5536
PA5558
PA5559
PA5568
PA5569
PA5570

### PR DESCRIPTION
**Pull request by vincerubinetti**
- increases width of search query column in multi gene search results
- fix network edge cutoff slider min value
- change multi gene search to exact search

closes #177 #178 #179

### CODE REVIEW

File: src/backend/genes.js [hunk 1]
```diff
@@ -18,11 +18,15 @@ export const urlGeneList = ({ organism, limit = maxLimit }) => {
...
+export const urlGeneSearch = ({
+  query,
+  exact = false,
+  limit = defaultLimit
+}) => {
   const params = new URLSearchParams();
   params.set('limit', limit);
   if (query)
-    params.set('autocomplete', query);
+    params.set(exact ? 'search' : 'autocomplete', query);
```
Comment (dongbohu) [inline src/backend/genes.js:29]: `search` is actually full text search, not exact search. I will add a new API parameter (something like `search-list`, which accepts a comma-separated list) to address it.

**Review by dongbohu — APPROVED** [review]

File: src/backend/genes.js (hunk 1 above)
Comment (vincerubinetti) [reply src/backend/genes.js:29]: i dont know the backend terms for this stuff. i dont find "search" or "autocomplete" to be very elucidating either. i just named this "exact" because in my testing it only ever returns a single result.

Comment (vincerubinetti) [reply src/backend/genes.js:29]: I can call it "precise" instead? I just need to make it clear to my future self, and I guess preferably without colliding with established backend terminology.

Also, are you talking about adding a single endpoint for multiple queries at the same time? When I was first making the app I would've asked for that, but now that I've implemented individual, multiple concurrent queries, I kinda like it that way. That way, the user gets a loading spinner for each query (instead of one big one for all of the queries), and sort of gets a progress update.

Comment (vincerubinetti) [reply src/backend/genes.js:29]: like this

Q0wEjQCZ95

Comment (dongbohu) [reply src/backend/genes.js:29]: Either `exact` or `precise` is good to me. (I prefer `exact` a little more.) 

The spinner for each search query seems fancy, but when a user types in a list of genes to search, I am not sure how much he cares about the individual search query's result. If you like it, I can implement an API parameter like `exact-search=xxx` which matches only genes whose names or aliases match `xxx` exactly (case-insensitive), instead of treating `xxx` as a comma-separated list. I will let you know when it is done.

Comment (vincerubinetti) [reply src/backend/genes.js:29]: When you have a really long list like in #177, it takes a while to query them all, and individual spinners to show progress is good. Unless combining the searches on the backend would be significantly faster.

So if I understand correctly, "exact" search means it looks for fields that essentially equal the query string (case insensitive), with nothing more and nothing less. And "full text" is more like substring matching, where you just find entries who contain that string in them. And then "autocomplete" is some sort of fuzzy search.

Idk if we need an exact search. I think substring/full-text might be enough. Let's what Deb thinks when testing out this PR.

Comment (dongbohu) [reply src/backend/genes.js:29]: Full text search is exact word search with word stems considered:
https://www.postgresql.org/docs/12/textsearch.html

I will hold the API change and wait for more user comments.

**Comment by vincerubinetti** [comment]
@cgreene Looks like Deb is probably too busy to look at this today. Should we just merge it? It would be very easy to switch back if they like it better the old way.

**Comment by cgreene** [comment]
Works for me 👍
